version: "3.5"
services:
  proshop-demo:
    image: proshop-demo
    ports:
      - "8080:8080"
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
  maildev:
    image: maildev/maildev
    command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
    ports:
      - "1080:1080"
      - "1025:1025"