spring:
  application:
    name: proshop-services
    environment: ${ENV:localhost}
  servlet:
    multipart:
      max-file-size: 50MB
  data:
    mongodb:
      uri: mongodb://docker:docker@localhost:27017/proshop?retryWrites=true&w=majority&authSource=admin

app:
  jwt:
    secret: 236229a6df55cd125ee5ad2c3318bc1a497b2ed94b1d1f3a2d4398639d3862fb=
    expiration-millis: 604800000
# SHA256 encode(proshop)
# 1day in ms

#
#  mail:
#    host: "${server.host}"
#    port: 1025
#    username: hello
#    password: hello
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: false
#          starttls:
#            enable: false
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

server:
  servlet:
    context-path: /proshop
  error:
    include-message: always # allows you to change the exception handling messages
    include-binding-errors: always
  port: 8080

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

logging:
  include-application-name: true